import sys

with open('F:\skillswap\lib\MainPage\chat\chatPage.dart', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
skip = False
for i, line in enumerate(lines):
    if '  Future<void> _sendMeetingMessage(DateTime meetingTime) async {' in line:
        skip = True
        new_lines.extend([
            "  Future<void> _sendMeetingMessage(DateTime meetingTime, int duration) async {\n",
            "    final chatRef = FirebaseFirestore.instance\n",
            "        .collection('chats')\n",
            "        .doc(widget.chatId)\n",
            "        .collection('messages');\n",
            "\n",
            "    await chatRef.add({\n",
            "      'senderId': 'system',\n",
            "      'type': 'system_meeting_created',\n",
            "      'meetingTime': Timestamp.fromDate(meetingTime),\n",
            "      'duration': duration,\n",
            "      'timestamp': FieldValue.serverTimestamp(),\n",
            "      'readBy': [],\n",
            "    });\n",
            "\n",
            "    await FirebaseFirestore.instance\n",
            "        .collection('chats')\n",
            "        .doc(widget.chatId)\n",
            "        .update({\n",
            "      'lastMessage': '?? Кездесу жоспарланды',\n",
            "      'lastTimestamp': FieldValue.serverTimestamp(),\n",
            "      'lastType': 'system_meeting_created',\n",
            "    });\n",
            "  }\n",
            "\n",
            "  void _showConfirmDialog(DateTime meetingTime) {\n",
            "    int _selectedDuration = 60;\n",
            "    showDialog(\n",
            "      context: context,\n",
            "      builder: (context) {\n",
            "        return StatefulBuilder(\n",
            "          builder: (context, setState) {\n",
            "            return AlertDialog(\n",
            "              backgroundColor: Colors.white,\n",
            "              title: const Text(\"Confirm Meeting\"),\n",
            "              content: Column(\n",
            "                mainAxisSize: MainAxisSize.min,\n",
            "                crossAxisAlignment: CrossAxisAlignment.start,\n",
            "                children: [\n",
            "                  Text(\n",
            "                    \"Meeting Time:\\n..  :\"),\n",
            "                  const SizedBox(height: 20),\n",
            "                  const Text(\"Duration (minutes):\"),\n",
            "                  Row(\n",
            "                    mainAxisAlignment: MainAxisAlignment.spaceBetween,\n",
            "                    children: [\n",
            "                      IconButton(\n",
            "                        icon: const Icon(Icons.remove_circle_outline),\n",
            "                        onPressed: _selectedDuration > 5\n",
            "                            ? () {\n",
            "                                setState(() {\n",
            "                                  _selectedDuration -= 5;\n",
            "                                });\n",
            "                              }\n",
            "                            : null,\n",
            "                      ),\n",
            "                      Text(\n",
            "                        \"\ min\",\n",
            "                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),\n",
            "                      ),\n",
            "                      IconButton(\n",
            "                        icon: const Icon(Icons.add_circle_outline),\n",
            "                        onPressed: _selectedDuration < 180\n",
            "                            ? () {\n",
            "                                setState(() {\n",
            "                                  _selectedDuration += 5;\n",
            "                                });\n",
            "                              }\n",
            "                            : null,\n",
            "                      ),\n",
            "                    ],\n",
            "                  ),\n",
            "                  Slider(\n",
            "                    value: _selectedDuration.toDouble(),\n",
            "                    min: 5,\n",
            "                    max: 180,\n",
            "                    divisions: 35,\n",
            "                    activeColor: const Color(0xFF1E88E5),\n",
            "                    onChanged: (double value) {\n",
            "                      setState(() {\n",
            "                        _selectedDuration = value.toInt();\n",
            "                      });\n",
            "                    },\n",
            "                  )\n",
            "                ],\n",
            "              ),\n",
            "              actions: [\n",
            "                TextButton(\n",
            "                  onPressed: () => Navigator.pop(context),\n",
            "                  child: const Text(\n",
            "                    \"Cancel\",\n",
            "                    style: TextStyle(color: Color(0xFF1E88E5)),\n",
            "                  ),\n",
            "                ),\n",
            "                OutlinedButton(\n",
            "                  onPressed: () async {\n",
            "                    Navigator.pop(context);\n",
            "                    await _sendMeetingMessage(meetingTime, _selectedDuration);\n",
            "                  },\n",
            "                  style: OutlinedButton.styleFrom(\n",
            "                    foregroundColor: const Color(0xFF1E88E5),\n",
            "                    side: const BorderSide(\n",
            "                      color: Color(0xFF1E88E5),\n",
            "                    ),\n",
            "                    shape: RoundedRectangleBorder(\n",
            "                      borderRadius: BorderRadius.circular(25),\n",
            "                    ),\n",
            "                    padding: const EdgeInsets.symmetric(\n",
            "                      horizontal: 15,\n",
            "                      vertical: 10,\n",
            "                    ),\n",
            "                  ),\n",
            "                  child: const Text(\"Confirm\"),\n",
            "                ),\n",
            "              ],\n",
            "            );\n",
            "          }\n",
            "        );\n",
            "      },\n",
            "    );\n",
            "  }\n\n"
        ])
    elif skip and 'Future<void> _openMeetingScheduler() async {' in line:
        skip = False
    
    if not skip:
        new_lines.append(line)

with open('F:\skillswap\lib\MainPage\chat\chatPage.dart', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print("Done")
